export const IMAGE_STORE = {
  ball: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/Artboard-9-300x300.png`,
  sport: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/Artboard-5-300x300-1.png`,
  slot: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/slot-1.png`,
  casino: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/casino.png`,
  bonus: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/pro.png`,
  ipad: `https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/call.png`,
  lineContact:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/ic-line-text.png`,
  banner1:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/Untitled-1.jpg`,
  banner2:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/04.jpg`,
  banner3:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/Untitled-1.jpg`,
  banner4:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/02.jpg`,
  banner5:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/04.jpg`,
  bg_welcome:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/review-index-cover-bg.39f58f66.jpg`,
  logo:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/logo.png`,
  women:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/wm-casino-info-banner-1-2.png`,
  sportCard:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/1-sbobet.png`,
  storeGame:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/1-allbet.png`,
  hotGameItem:`https://ideabet.org/theme/mcblue/wp-content/uploads/2022/08/1-joker.png`,
}